[package]
name = "cardsnif"
version = "0.1.0"
authors = []

[lib]
name = "cardsnif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
lazy_static = "1.0"
rand = "0.6"
rustler = "0.20.0"
rustler_codegen = "0.20.0"